version = 1
SPDX-PackageName = "magiclane-maps-sdk-flutter-ios"
SPDX-PackageSupplier = "magiclane-developer@users.noreply.github.com"
SPDX-PackageDownloadLocation = "https://github.com/magiclane/magiclane-maps-sdk-flutter-ios"
SPDX-PackageComment = "iOS support layer of MagicLane Maps SDK for Flutter."

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023-2026 Magic Lane International B.V. <info@magiclane.com>"
SPDX-License-Identifier = "LicenseRef-MagicLane-Proprietary"
